### ISSUE TITLE
Error: error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by seiya303** [Pionier2027/recopi#3]
An unexpected error occurred when I tried reexecuting docker-compose, which had been configured without problems before. I'm tackling this issue until it is solved.

Refer to: https://github.com/webpack/webpack/issues/14532

`Error: error:0308010C:digital envelope routines::unsupported  at new Hash (node:internal/crypto/hash:67:19)  at Object.createHash (node:crypto:130:10)  at module.exports (/app/frontend/node_modules/webpack/lib/util/createHash.js:135:53)  at NormalModule._initBuildHash (/app/frontend/node_modules/webpack/lib/NormalModule.js:417:16)  at handleParseError (/app/frontend/node_modules/webpack/lib/NormalModule.js:471:10)  at /app/frontend/node_modules/webpack/lib/NormalModule.js:503:5  at /app/frontend/node_modules/webpack/lib/NormalModule.js:358:12  at /app/frontend/node_modules/loader-runner/lib/LoaderRunner.js:373:3  at iterateNormalLoaders (/app/frontend/node_modules/loader-runner/lib/LoaderRunner.js:214:10)  at iterateNormalLoaders (/app/frontend/node_modules/loader-runner/lib/LoaderRunner.js:221:10)  /app/frontend/node_modules/react-scripts/scripts/start.js:19  throw err;`

**Comment by seiya303** [comment]
Solved this issue by changing `"start": "react-scripts start",` into `"start": "react-scripts --openssl-legacy-provider start",` in package.json file.
